package com.plcoding.composeswipeablepages.common

import com.plcoding.composeswipeablepages.R
import com.plcoding.composeswipeablepages.game_feature.viewmodel.ModelCell
import com.plcoding.composeswipeablepages.game_feature.viewmodel.StateCell
import com.plcoding.composeswipeablepages.levels_feature.model.LevelParams

enum class SizeField(val count:Int) {
    Size2x2(2), Size3x3(4), Size4x4(8), Size5x5(12)
}

var listLevels = listOf(

    listOf(
        ModelCell(index = 0, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 1, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 2, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 3, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one)
    ),
    listOf(
        ModelCell(index = 0, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 1, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 2, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 3, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one)
    ),
    listOf(
        ModelCell(index = 0, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 1, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 2, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 3, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one)
    ),
    listOf(
        ModelCell(index = 0, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 1, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 2, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 3, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
    ),

    listOf(
        ModelCell(index = 0, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 1, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 2, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 3, img = R.drawable.empty_card, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 4, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 5, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 6, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 7, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 8, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one)
    ),

    listOf(
        ModelCell(index = 0, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 1, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 2, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 3, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 4, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 5, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 6, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 7, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 8, img = R.drawable.empty_card, stateCell = StateCell.StartCheckCell_one),
    ),

    listOf(
        ModelCell(index = 0, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 1, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 2, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 3, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 4, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 5, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 6, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 7, img = R.drawable.empty_card, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 8, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
    ),
    listOf(
        ModelCell(index = 0, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 1, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 2, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 3, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 4, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 5, img = R.drawable.empty_card, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 6, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 7, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 8, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
    ),
    listOf(
        ModelCell(index = 0, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 1, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 2, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 3, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 4, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 5, img = R.drawable.empty_card, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 6, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 7, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 8, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
    ),
    listOf(
        ModelCell(index = 0, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 1, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 2, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 3, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 4, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 5, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 6, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 7, img = R.drawable.empty_card, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 8, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
    ),


    listOf(
        ModelCell(index = 0, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 1, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 2, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 3, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 4, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 5, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 6, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 7, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 8, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 9, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 10, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 11, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 12, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 13, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 14, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 15, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
    ),

    listOf(
        ModelCell(index = 0, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 1, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 2, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 3, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 4, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 5, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 6, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 7, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 8, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 9, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 10, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 11, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 12, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 13, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 14, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 15, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
    ),

    listOf(
        ModelCell(index = 0, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 1, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 2, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 3, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 4, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 5, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 6, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 7, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 8, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 9, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 10, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 11, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 12, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 13, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 14, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 15, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
    ),

    listOf(
        ModelCell(index = 0, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 1, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 2, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 3, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 4, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 5, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 6, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 7, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 8, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 9, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 10, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 11, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 12, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 13, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 14, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 15, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
    ),

    listOf(
        ModelCell(index = 0, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 1, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 2, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 3, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 4, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 5, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 6, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 7, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 8, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 9, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 10, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 11, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 12, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 13,img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 14, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 15, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
    ),

    listOf(
        ModelCell(index = 0, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 1, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 2, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 3, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 4, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 5, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 6, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 7, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 8, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 9, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 10, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 11, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 12, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 13, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 14, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 15, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),),
    listOf(
        ModelCell(index = 0, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 1, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 2, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 3, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 4, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 5, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 6, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 7, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 8, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 9, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 10, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 11, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 12, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 13, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 14, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 15, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
    ),

    listOf(
        ModelCell(index = 0, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 1, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 2, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 3, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 4, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 5, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 6, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 7, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 8, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 9, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 10, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 11, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 12, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 13, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 14, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 15, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
    ),

    listOf(
        ModelCell(index = 0, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 1, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 2, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 3, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 4, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 5, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 6, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 7, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 8, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 9, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 10, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 11, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 12, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 13, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 14, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 15, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one
        ),
    ),

    listOf(
        ModelCell(index = 0, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 1, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 2, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 3, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 4, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 5, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 6, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 7, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 8, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 9, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 10, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 11, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 12, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 13, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 14, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 15, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
    ),


    listOf(
        ModelCell(index = 0, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 1, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 2, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 3, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 4, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 5, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 6, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 7, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 8, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 9, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 10, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 11, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 12, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 13, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 14, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 15, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 16, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 17, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 18, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 19, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 20, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 21, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 22, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 23, img = R.drawable.empty_card, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 24, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),

        ),
    listOf(
        ModelCell(index = 0, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 1, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 2, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 3, img = R.drawable.empty_card, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 4, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 5, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 6, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 7, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 8, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 9, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 10, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 11, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 12, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 13, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 14, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 15, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 16, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 17, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 18, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 19, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 20, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 21, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 22, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 23, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 24, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ),
    listOf(ModelCell(index = 0, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 1, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 2, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 3, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 4, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 5, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 6, img = R.drawable.empty_card, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 7, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 8, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 9, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 10, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 11, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 12, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 13, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 14, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 15, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 16, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 17, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 18, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 19, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 20, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 21 , img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 22, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 23, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 24, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ),
    listOf(
        ModelCell(index = 0, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 1, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 2, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 3, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 4, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 5, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 6, img = R.drawable.empty_card, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 7, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 8, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 9, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 10, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 11, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 12, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 13, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 14, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 15, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 16, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 17, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 18, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 19, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 20, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 21, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 22, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 23, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 24, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
    ),
    listOf(
        ModelCell(index = 0, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 1, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 2, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 3, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 4, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 5, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 6, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 7, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 8, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 9, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 10, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 11, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 12, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 13, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 14, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 15, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 16, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 17, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 18, img = R.drawable.empty_card, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 19, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 20, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 21, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 22, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 23, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 24, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one)
    ),
    listOf(
        ModelCell(index = 0, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 1, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 2, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 3, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 4, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 5, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 6, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 7, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 8, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 9, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 10, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 11, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 12, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 13, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 14, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 15, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 16, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 17, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 18, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 19, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 20, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 21, img = R.drawable.empty_card, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 22, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 23, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 24, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
    ),
    listOf(
        ModelCell(index = 0, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 1, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 2, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 3, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 4, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 5, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 6, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 7, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 8, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 9, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 10, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 11, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 12, img = R.drawable.empty_card, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 13, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 14, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 15, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 16, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 17, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 18, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 19, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 20, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 21, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 22, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 23, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 24, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
    ),
    listOf(
        ModelCell(index = 0, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 1, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 2, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 3, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 4, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 5, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 6, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 7, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 8, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 9, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 10, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 11, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 12, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 13, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 14, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 15, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 16, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 17, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 18, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 19, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 20, img = R.drawable.card_game_potion,stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 21, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 22, img = R.drawable.empty_card, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 23, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 24, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
    ),
    listOf(
        ModelCell(index = 0, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 1, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 2, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 3, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 4, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 5, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 6, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 7, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 8, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 9, img = R.drawable.card_game_potion,stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 10, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 11, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 12, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 13, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 14, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 15, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 16, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 17, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 18, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 19, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 20, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 21, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 22, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 23, img = R.drawable.empty_card, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 24, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
    ),
    listOf(
        ModelCell(index = 0, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 1, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 2, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 3, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 4, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 5, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 6, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 7, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 8, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 9, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 10, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 11, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 12, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 13, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 14, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 15, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 16, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 17, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 18, img = R.drawable.game_card_book, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 19,img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 20, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 21, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 22, img = R.drawable.card_game_hat, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 23, img = R.drawable.empty_card, stateCell = StateCell.StartCheckCell_one),
        ModelCell(index = 24, img = R.drawable.card_game_potion, stateCell = StateCell.StartCheckCell_one),
    )
)

val levelImage = listOf(
    LevelParams(0, R.drawable.one_level),
    LevelParams(1, R.drawable.two_level),
    LevelParams(2, R.drawable.three_level),
    LevelParams(3, R.drawable.four_level),
    LevelParams(4, R.drawable.fife_level),
    LevelParams(5, R.drawable.six_level),
    LevelParams(6, R.drawable.seven_level),
    LevelParams(7, R.drawable.eight_level),
    LevelParams(8, R.drawable.nine_level),
    LevelParams(9, R.drawable.ten_level),
    LevelParams(10, R.drawable.eleven_level),
    LevelParams(11, R.drawable.twelve_level),
    LevelParams(12, R.drawable.thirty_level),
    LevelParams(13, R.drawable.fourty_level),
    LevelParams(14, R.drawable.fifty_level),
    LevelParams(15, R.drawable.sixteen_level),
    LevelParams(16, R.drawable.seventeen_level),
    LevelParams(17, R.drawable.eigteen_level),
    LevelParams(18, R.drawable.ninteen_level),
    LevelParams(19, R.drawable.twenty_level),
    LevelParams(20, R.drawable.twenty_one_level),
    LevelParams(21, R.drawable.twenty_two_level),
    LevelParams(22, R.drawable.twenty_three_level),
    LevelParams(23, R.drawable.twenty_four_level),
    LevelParams(24, R.drawable.twenty_fife_level),
    LevelParams(25, R.drawable.twenty_six_level),
    LevelParams(26, R.drawable.twenty_seven_level),
    LevelParams(27, R.drawable.twenty_eight_level),
    LevelParams(28, R.drawable.twenty_nine_level),
    LevelParams(29, R.drawable.threety_level),
)
